DROP DATABASE IF EXISTS maildelay;
DROP ROLE IF EXISTS maildelay;

CREATE USER maildelay WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN PASSWORD 'vagrant';
CREATE DATABASE maildelay WITH TEMPLATE = template0 OWNER = maildelay;
